### ISSUE TITLE
画像内容の間違い

### ISSUE THREAD

**Issue by SuperTaiyaki** [Taro-Hayashi/Handyman#1]
大した問題ではありませんが、組立中にちょっと引っかかった２点です。
IMG_5108.jpgでURAと書いてありますが、表です。
IMG_5131.jpgで、左上のスペーサーに青いマルはありません

**Comment by Taro-Hayashi** [comment]
ご報告ありがとうございます！混乱させてしまい申し訳ありませんでした。
見直してみたところ裏ではないのにURAになっている画像は他にもありました。近日中に直します。

**Comment by Taro-Hayashi** [comment]
プルリクもありがとうございました！他の画像も訂正しました。
